//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fileupload.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.UploadFiles = new HashSet<UploadFile>();
            this.NewUploadFiles = new HashSet<NewUploadFile>();
        }
    
        public string StudentId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<UploadFile> UploadFiles { get; set; }
        public virtual ICollection<NewUploadFile> NewUploadFiles { get; set; }
    }
}
